# Generated by Django 3.2.12 on 2022-02-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_avodhaa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
